/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.keva.dbutil;

import picocli.CommandLine;

public class App {
    public static void main(String[] args) {
        System.exit(new CommandLine(new ConvertCommand()).execute(args));
    }
}
